### PR TITLE
Clickable actions

### PR DESCRIPTION
**Pull request by plukevdh**
I added two methods:

`close_on_click` _(boolean | optional)_: Notification widget will close on click (anywhere within the widget) if set to true.
`on_click` _(function | optional)_: Allow a function to be bound to to the widget being clicked.

Pretty simple changes. Documentation (faux-tests) added to the index.html file. Recompressed via the YUI Compressor

### CODE REVIEW

**Comment by myusuf3** [comment]
I would fix your issue with tabs vs. spaces and then request the pull again. I would assume the repo owner would like to keep it consistent.

**Comment by plukevdh** [comment]
good call. fixed with just the updated code sans-whitespace changes.

**Comment by plukevdh** [comment]
@myusuf3 pull still open. cleaning out my open requests. Please pull or close.

**Comment by myusuf3** [comment]
@plukevdh I was just helping out, I can't do either.

**Comment by plukevdh** [comment]
@myusuf3 Ah sorry 

@jboesch meant for you

**Pull request closed without merging**
